/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalisisRouteImport } from './routes/analisis'
import { Route as MetodologiRouteImport } from './routes/metodologi'
import { Route as AnalisisIndexRouteImport } from './routes/analisis.index'
import { Route as AnalisisPlatformRouteImport } from './routes/analisis.$platform'
import { Route as AnalisisSektorSectorRouteImport } from './routes/analisis.sektor.$sector'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalisisRoute = AnalisisRouteImport.update({
  id: '/analisis',
  path: '/analisis',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodologiRoute = MetodologiRouteImport.update({
  id: '/metodologi',
  path: '/metodologi',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalisisIndexRoute = AnalisisIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AnalisisRoute,
} as any)
const AnalisisPlatformRoute = AnalisisPlatformRouteImport.update({
  id: '/$platform',
  path: '/$platform',
  getParentRoute: () => AnalisisRoute,
} as any)
const AnalisisSektorSectorRoute = AnalisisSektorSectorRouteImport.update({
  id: '/sektor/$sector',
  path: '/sektor/$sector',
  getParentRoute: () => AnalisisRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analisis': typeof AnalisisRouteWithChildren
  '/metodologi': typeof MetodologiRoute
  '/analisis/$platform': typeof AnalisisPlatformRoute
  '/analisis/': typeof AnalisisIndexRoute
  '/analisis/sektor/$sector': typeof AnalisisSektorSectorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/metodologi': typeof MetodologiRoute
  '/analisis/$platform': typeof AnalisisPlatformRoute
  '/analisis': typeof AnalisisIndexRoute
  '/analisis/sektor/$sector': typeof AnalisisSektorSectorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analisis': typeof AnalisisRouteWithChildren
  '/metodologi': typeof MetodologiRoute
  '/analisis/$platform': typeof AnalisisPlatformRoute
  '/analisis/': typeof AnalisisIndexRoute
  '/analisis/sektor/$sector': typeof AnalisisSektorSectorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analisis'
    | '/metodologi'
    | '/analisis/$platform'
    | '/analisis/'
    | '/analisis/sektor/$sector'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/metodologi'
    | '/analisis/$platform'
    | '/analisis'
    | '/analisis/sektor/$sector'
  id:
    | '__root__'
    | '/'
    | '/analisis'
    | '/metodologi'
    | '/analisis/$platform'
    | '/analisis/'
    | '/analisis/sektor/$sector'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalisisRoute: typeof AnalisisRouteWithChildren
  MetodologiRoute: typeof MetodologiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analisis': {
      id: '/analisis'
      path: '/analisis'
      fullPath: '/analisis'
      preLoaderRoute: typeof AnalisisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodologi': {
      id: '/metodologi'
      path: '/metodologi'
      fullPath: '/metodologi'
      preLoaderRoute: typeof MetodologiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analisis/': {
      id: '/analisis/'
      path: '/'
      fullPath: '/analisis/'
      preLoaderRoute: typeof AnalisisIndexRouteImport
      parentRoute: typeof AnalisisRoute
    }
    '/analisis/$platform': {
      id: '/analisis/$platform'
      path: '/$platform'
      fullPath: '/analisis/$platform'
      preLoaderRoute: typeof AnalisisPlatformRouteImport
      parentRoute: typeof AnalisisRoute
    }
    '/analisis/sektor/$sector': {
      id: '/analisis/sektor/$sector'
      path: '/sektor/$sector'
      fullPath: '/analisis/sektor/$sector'
      preLoaderRoute: typeof AnalisisSektorSectorRouteImport
      parentRoute: typeof AnalisisRoute
    }
  }
}

interface AnalisisRouteChildren {
  AnalisisPlatformRoute: typeof AnalisisPlatformRoute
  AnalisisIndexRoute: typeof AnalisisIndexRoute
  AnalisisSektorSectorRoute: typeof AnalisisSektorSectorRoute
}

const AnalisisRouteChildren: AnalisisRouteChildren = {
  AnalisisPlatformRoute: AnalisisPlatformRoute,
  AnalisisIndexRoute: AnalisisIndexRoute,
  AnalisisSektorSectorRoute: AnalisisSektorSectorRoute,
}

const AnalisisRouteWithChildren = AnalisisRoute._addFileChildren(
  AnalisisRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalisisRoute: AnalisisRouteWithChildren,
  MetodologiRoute: MetodologiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
